/*
 * This file is generated by jOOQ.
 */
package adiitya.adisrealm.db;


import adiitya.adisrealm.db.tables.Names;
import adiitya.adisrealm.db.tables.Nicknames;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -2124552120;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>names</code>.
     */
    public final Names NAMES = adiitya.adisrealm.db.tables.Names.NAMES;

    /**
     * The table <code>nicknames</code>.
     */
    public final Nicknames NICKNAMES = adiitya.adisrealm.db.tables.Nicknames.NICKNAMES;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Names.NAMES,
            Nicknames.NICKNAMES);
    }
}
