name: AdisRealm
version: 0.2
main: adiitya.adisrealm.AdisRealm
load: STARTUP
depend: [SmartInvs]
api-version: 1.13
commands:
  nick:
    description: Used to manage nicknames
    usage: /nick <add | remove | list>
    aliases: [nick]
  msg:
    description: Sends a message to a player
    usage: /msg <player> <message>
    aliases: [msg]
  r:
    description: Used to reply to the last person you messaged
    usage: /r <message>
    aliases: [r]
  afk:
    usage: /afk [reason]
    aliases: [afk]
  settings:
    usage: /settings
    aliases: [settings, s]