name: AdisRealm
version: 0.2
main: adiitya.adisrealm.AdisRealm
load: STARTUP
commands:
  nickname:
    description: Used to manage nicknames
    usage: /nick <add | remove | list>
    aliases: [nickname, nick]
  msg:
    description: Sends a message to a player
    usage: /msg <player> <message>
    aliases: [msg]
  r:
    description: Used to reply to the last person you messaged
    usage: /r <message>
    aliases: [r]
  afk:
    usage: /afk [reason]
    aliases: [afk]