/*
 * This file is generated by jOOQ.
 */
package adiitya.adisrealm.db;


import adiitya.adisrealm.db.tables.Nicknames;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>nicknames</code>.
     */
    public static final Nicknames NICKNAMES = adiitya.adisrealm.db.tables.Nicknames.NICKNAMES;
}
